### PR TITLE
Pupil Signature Verification Process

### PR DESCRIPTION
**Pull request by johannesKnoll**
We worked on the automated signature process, where pupil or parents can sign their certificates.

Note:
The current changes cannot be seen by end-users as no "automated" certificates can be created at the moment.
This will be part of a separate pull request.

The certificates tab will still also be invisible for non tutors, as it now only gets shown if a certificate is present (which won't be there for non tutors).

### CODE REVIEW

**Comment by Jonasdoubleyou** [comment]
Backend part was shipped with https://github.com/corona-school/backend/pull/171

**Review by lsc0498 — APPROVED** [review]
Looks very good to me. Thank you very much everyone!🎉
However we should wait with the deployment until the modal for requesting a new certificate is adapted to the new process. I'm currently awaiting input from @tobiasbork on that issue.

**Comment by Jonasdoubleyou** [comment]
@lsc0498 mm, I don't see a reason not to merge it yet. Users won't see it, and we don't have the burden of keeping this branch up to date with master. IMO the branch should be merged now.

**Comment by lsc0498** [comment]
No worries @Jonasdoubleyou, I will adapt the request certificate modal this evening and deploy it afterwards 🙂

**Pull request merged**
